name: Trigger auto deployment for krmittaca02

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/krmittaca02-AutoDeployTrigger-7d940434-6a98-4083-b231-94669c49f6e8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.KRMITTACA02_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.KRMITTACA02_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.KRMITTACA02_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.KRMITTACA02_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.KRMITTACA02_REGISTRY_PASSWORD }}
          containerAppName: krmittaca02
          resourceGroup: expresssample903f8d04
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


